services:
  keycloak:
    image: 'mykeycloak'
    container_name: 'mykeycloak-container'
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=oracle
      - KC_DB_URL=jdbc:oracle:thin:@oracledb:1521/ORCLCDB
      - KC_DB_USERNAME=c##test1
      - KC_DB_PASSWORD=passowrd
      - KC_DB_DRIVER=oracle.jdbc.OracleDriver
      - KC_DB_SSL=false
      - QUARKUS_DATASOURCE_XA=false

    depends_on:
      - oracledb

  oracledb:
    image: oracle/database:19.3.0-ee
    container_name: oracledb
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=Nimrat16122023
